services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: frontend-react-group-dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: frontend-react-group-prod
    ports:
      - 3000:80
    volumes:
      - /app/node_modules
    restart: always

  storybook:
    build:
      context: .
      dockerfile: Dockerfile.storybook
    image: frontend-react-group-storybook
    ports:
      - 6006:6006
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
